name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - "renovate/**"
      - "!renovate/lock-file-maintenance"

jobs:
  CI:
    strategy:
      fail-fast: false

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.x.x

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm

      - name: install dependencies
        run: pnpm install

      - name: check formatting
        run: pnpm format:check

      - name: run linter
        run: pnpm lint

      - name: build
        run: pnpm build

      #- name: run tests
      #  run: pnpm test
